version: 2.1

jobs:
    deploy:
        docker:
            - image: arvindr226/alpine-ssh
        steps:
            - run: ssh -oStrictHostKeyChecking=no -v ubuntu@ec2-3-12-106-224.us-east-2.compute.amazonaws.com "./deploy.sh"

workflows:
    deploy-to-ec2:
        jobs:
            - deploy
